<h1>CMSC 197 Quiz 1</h1>
<h4>Jan Kristine A. Mosong</h4>
<p>201950084</p>

<h2>Part 1</h2>

In [2]:
import numpy as np

<h6>Create 2 1D arrays, y_hat and y</h6>

<p> Initialize y_hat with 20 linearly spaced numbers between -1 and 1</p>

In [3]:
y_hat = np.linspace(-1,1,20)
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

<p> Initialize y with 20 linearly spaced numbers between 0 and 1</p>

In [4]:
y = np.linspace(0,1,20)
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

<h6>Compute for the shape and dimension of y_hat and y.</h6>

<p>y_hat</p>

In [7]:
#shape of y_hat
y_hat.shape

(20,)

In [8]:
#dimension of y_hat
y_hat.ndim

1

<p>y</p>

In [9]:
#shape of y
y.shape

(20,)

In [10]:
#dimension of y
y.ndim

1

<h6>Create individual functions for each of the loss functions with y and y_hat as parameters</h6>

<p>Mean Squared Error (MSE)</p>

In [11]:
def mse(a,b):
    return np.mean(np.square(np.subtract(a,b)))

mse(y_hat,y)

0.3421052631578948

<p>Mean Absolute Error (MAE)</p>

In [12]:
def mae(a,b):
    return np.mean(np.abs(np.subtract(a,b)))

mae(y_hat,y)

0.4999999999999999

<p>Mean Squared Logarithmic Eror</p>
<p>(produces an error as log(0) is undefined)</p>

In [14]:
def msle(a,b):
    return np.mean(np.square(np.subtract(np.log(a+1),np.log(b+1))))

msle(y_hat,y)

C:\Users\Jenny\AppData\Local\Temp\ipykernel_11936\4166242169.py:2: RuntimeWarning: divide by zero encountered in log
  return np.mean(np.square(np.subtract(np.log(a+1),np.log(b+1))))


inf

<p>Mean Absolute Percentage Error (MAPE)</p>

In [15]:
def mape(a,b):
    return np.mean(np.abs(np.divide(np.subtract(a,b),a)))*100

mape(y_hat,y)

202.65927536515775

<h2>Part 2</h2>

<h6>Create a 1d array M {1, 2, …16} using the arange function</h6>

In [16]:
M = np.arange(1,17)
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

<h6>Reshape M into 4x4 array and store it to N</h6>

In [17]:
N = np.reshape(M, (4,4))
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

<h6>Get the 2nd row of N</h6>

In [19]:
N[1]

array([5, 6, 7, 8])

<h6>Get the minimum values for each column of N</h6>

In [20]:
np.amin(N,axis=0)

array([1, 2, 3, 4])

<h6>Get the locations of the minimum values for each column of N</h6>

In [21]:
temp = np.where(N==np.amin(N,axis=0))
temparray = np.asarray(temp)
#location of the minimum values at each column
index = set(zip(temparray[0],temparray[1]))
index

{(0, 0), (0, 1), (0, 2), (0, 3)}

<h6>Get the average of the whole matrix</h6>

In [23]:
np.average(N)

8.5

<h6>Create a vector V with 4 elements, each element is 1</h6>

In [25]:
V = np.ones(4, dtype=int)
V

array([1, 1, 1, 1])

In [26]:
np.dot(N,V)

array([10, 26, 42, 58])